language: node_js
node_js: stable
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
    - yarn install
script:
    - yarn run test
    - yarn docs:build
    - bash .travis/gen_ghpage.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs/.vuepress/dist
  keep_history: true
  target_branch: gh-pages
  verbose: true
  on:
    branch: master