language: node_js
node_js: stable
cache: npm
before_install:
  - npm config set scripts-prepend-node-path true
install:
  - npm ci
script:
  - npm run test
  - npm run docs:publish
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs/.vuepress/dist
  keep_history: true
  target_branch: gh-pages
  verbose: true
  on:
    branch: master
